modLoader="javafml" #mandatory
loaderVersion="[40,)"
license="All rights reserved"

[[mods]] #mandatory
modId="voxelmap" #mandatory
version="${file.jarVersion}" #mandatory
displayName="VoxelMap" #mandatory
logoFile="icon.png" #optional
credits="Thanks for this example mod goes to Java" #optional
authors="MamiyaOtaru"
description='''
Minimap and world map
'''

[[dependencies.voxelmap]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="CLIENT"

[[dependencies.voxelmap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"