modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"

[[mods]]
modId="voxelmap"
version="${file.jarVersion}"
displayName="VoxelMap"
logoFile="icon.png"
authors="MamiyaOtaru"
description='''
Minimap and world map
'''

[[dependencies.voxelmap]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.voxelmap]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="CLIENT"