modLoader="javafml"
loaderVersion="[37,)"
license="All rights reserved"

[[mods]]
modId="voxelmap"
version="${file.jarVersion}"
displayName="VoxelMap"
logoFile="icon.png"
# credits="Thanks for this example mod goes to Java"
authors="MamiyaOtaru"
description='''
Minimap and world map
'''
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
